### ISSUE TITLE
Need PciManager Library

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prampec/arduino-softtimer#1]
```
What steps will reproduce the problem?
1. I down loaded the Softtimer library 
2. Next when every I run the examples but kep getting complier errors

Solution
There errors were resolved by down loading the PciManager library
```

Original issue reported on code.google.com by `JDMANDEV...@AEP.COM` on 13 Dec 2012 at 1:22

**Comment by prampec** [comment]
Find new location for PciManager: https://github.com/prampec/arduino-pcimanager/releases

**Comment by ioddevs** [comment]
Hi.. just started to play around with your lib. awesome!!
but... Is it really necessary to have dependency to pcimanager?

It still failed. eventhough pcimanager is in my lib
<arduino>\libraries\arduino-pcimanager-2.1.0

Currently i removed Debouncer and Rotary from compilation.

In file included from 
<arduino>\libraries\arduino-softtimer-3.1.0\src\Rotary.cpp:28:0:
<arduino>\00.wa\libraries\arduino-softtimer-3.1.0\src\Rotary.h:31:25: 
fatal error: PciListener.h: No such file or directory
 #include <PciListener.h>

**Comment by prampec** [comment]
Yes, it is necessary to have the PciManager library installed.
It seems, that there is now way to avoid that, even if you don't actually call any of it's functions.
But don't worry, you will need it sooner or later any way, as reading data from digital pins you will use the Debouncer. :)

**Comment by prampec** [comment]
You can install PciManager library directly from the Library Manager of the Arduino IDE. See the following link for how to do that: https://www.arduino.cc/en/Guide/Libraries#toc3
