### ISSUE TITLE
SoftTimer Error 

### ISSUE THREAD

**Issue by A-Amin** [prampec/arduino-softtimer#10]
I added both softtimer 3.1 and pcimanager  2.1.2 , although i get the pcilistener.h include error what should i do

**Comment by prampec** [comment]
Sorry! I don't know how to help you. As far as I know, if you install both libraries from the Library Manager, everything should work fine. You might try to:
- Include the PciListener.h in your code, so Arduino will know, that this library also need to be compiled.
- Try to use different Arduino version.
  Please let me know if something helped you out!
