### ISSUE TITLE
Problem - Task taskCycle( 100, Cycle) throws error: Cycle not declared in this scope

### ISSUE THREAD

**Issue by PhilRounds** [prampec/arduino-softtimer#11]
Environment:
SoftTimer v3.1.0, PciManager 2.1.0, Arduino 1.6.7

My code:
# include <PciManager.h>
# include <PciListenerImp.h>
# include <PciListener.h>
# include <Adafruit_MotorShield.h>
# include <stdlib.h>
# include <Wire.h>
# include "utility/Adafruit_PWMServodriver.h"
# include <SoftTimer.h>

....
Task taskCycle( 100, Cycle);  // This line throws the error
...

void setup() {
...
  SoftTimer.add(&taskCycle);  
}
void Cycle(Task\* me)
{
  ... Either my code, or I just comment it all out, it doesn't matter.
}

If I run the same program in a different environment, it works
Arduino 1.6.1, I can't find the version# for PciManager or for SoftTimer on the pc it runs on, they're both 2014 versions.

Any suggestions?

**Comment by prampec** [comment]
Please take a look at this issue:
https://github.com/prampec/arduino-softtimer/issues/6

Is this what you are looking for?
