### ISSUE TITLE
SoftTimer7Heartbeat

### ISSUE THREAD

**Issue by snikhilchoudhary** [prampec/arduino-softtimer#16]
error while compiling- myLoop was not declared in this scope. The following is the error message-

Arduino: 1.6.9 (Windows 10), Board: "Arduino Nano, ATmega328"

SoftTimer7Heartbeat:15: error: 'myLoop' was not declared in this scope

 Task t1(0, myLoop);

            ^

exit status 1
'myLoop' was not declared in this scope

**Comment by prampec** [comment]
Please consult issue #6
