### ISSUE TITLE
Is any way to delete task? 

### ISSUE THREAD

**Issue by stavinsky** [prampec/arduino-softtimer#17]
Hello! Thanks for awesome lib. 
I have a question. Can I stop or pause task for a while and start it again from another task?

**Comment by prampec** [comment]
Yes. You can remove and add any tasks any time.
So, if you want to "pause" a task, you can remove it from the timer manager [SoftTimer.add(&mytask);]. To start it again, simply add again [SoftTimer.add(&mytask);].
You can find a quite complex project with SoftTimer here: https://doc.csipa.hu/?p=288
