### ISSUE TITLE
Regression of Rotary encoder

### ISSUE THREAD

**Issue by fredilarsen** [prampec/arduino-softtimer#33]
I have been using this library for some years, thanks.

I recently found that when reflashing a device that I have had in operation for years, the rotary encoder stopped working. After some trial and error I found that it works great with SoftTimer up to version 3.1.5 but not with 3.2.0 which is the last available in Arduino Studio.

Symptoms with v3.2: Rotary encoder movement not being picked up at all, at least the callback is not called.

**Comment by prampec** [comment]
Have you noticed, that init() is now required to be called in setup? (See examples!)

**Comment by fredilarsen** [comment]
Init was not called in my code, so I will add that and retest. Thank you.
I assumed the API was unchanged as it was only a minor version upgrade from 3.1.5 to 3.2.0.

**Comment by prampec** [comment]
Well, yes. You might be right on that it was not emphasized well.
Thanks for the feedback any way!

**Comment by fredilarsen** [comment]
Thanks for the help!
