### ISSUE TITLE
Could you ask for inclusion of this library in Arduino's Library Manager?

### ISSUE THREAD

**Issue by q2dg** [prampec/arduino-softtimer#4]
This would give more visibility to this library, I think.
Thanks

**Comment by prampec** [comment]
Sorry, I've missed these comments.
What do you mean on Library Manager?

**Comment by q2dg** [comment]
This: https://www.arduino.cc/en/Guide/Libraries#toc3
And this: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by prampec** [comment]
Cool! I will definitely do this. Thank you for your advise!

**Comment by prampec** [comment]
Done.
