### ISSUE TITLE
Compilition errors

### ISSUE THREAD

**Issue by mikekgr** [prampec/arduino-softtimer#8]
Dear Sirs,
I have installed your latest version of arduino-softtimer at my Arduino (I tested in both 1.0.5-r2 and 1.6.4 running in Windows 7) but I get the following errors when try to get compile the example SoftTimer1Task.ino (but I get same errors on the others)   :  

In file included from C:\Users\mikek\leonidas.kranidis@gmail.com\Arduino-Latest Full\libraries\arduino_softtimer\Debouncer.cpp:28:
C:\Users\mikek\leonidas.kranidis@gmail.com\Arduino-Latest Full\libraries\arduino_softtimer\/Debouncer.h:47: error: expected class-name before ',' token
C:\Users\mikek\leonidas.kranidis@gmail.com\Arduino-Latest Full\libraries\arduino_softtimer\/Debouncer.h:72: error: ISO C++ forbids initialization of member 'debounceDelayMicros'
C:\Users\mikek\leonidas.kranidis@gmail.com\Arduino-Latest Full\libraries\arduino_softtimer\/Debouncer.h:72: error: making 'debounceDelayMicros' static
C:\Users\mikek\leonidas.kranidis@gmail.com\Arduino-Latest Full\libraries\arduino_softtimer\/Debouncer.h:72: error: ISO C++ forbids in-class initialization of non-const static member 'debounceDelayMicros'

What do you believe is wrong? What can I do in order to have this library working?

Thanks and Best Regards.

**Comment by prampec** [comment]
This "ISO C++ forbids..." seems to be a bug in the Arduino, as in 1.6.5, and 1.6.6 this does not appear any more.
The "Debouncer.h:47: error: expected class-name before ',' token" says, that SoftTimer depends on PciManager library, that you need to install parallel. (See https://github.com/prampec/arduino-softtimer/issues/1 for details.)
